### PR TITLE
#168050026 Hosts should be able to add their accommodation facilities

### PR DESCRIPTION
**Pull request by Jordybastien**
#### What does this PR do?
This PR allows hosts to add their accommodation facilities
#### Description of Task to be completed?

- Add endpoint to add Host

- Send email to Host of his credentials

- Reset Host credentials

- Add accommodation

- Add rooms to accommodation

- View all accommodations

- View all accommodations within a location

- View single accommodation

- View all rooms within an accommodation

- View single room within an accommodation

#### How should this be manually tested?
1. Start by cloning repository
`git clone https://github.com/andela/technites-bn-backend.git`

2. Then checkout to this branch
`git checkout ft-hosts-can-add-accommodations-168050026`

3. Run `npm run install`

4. Run `npm run migrate`

5. Run `npm run seed` this will add two locations with id `1` and `2` that you will need in testing the feature.

6. Start server  `npm run  dev`

7. login with your superadmin account and head to the route `/api/v1/hosts` with `POST` method, fill in the hosts `email`, `firstname` and `lastname`, It will send an email to the host with his new credentials auto generated password that may letter be reset, by preference use your own email for this.

8. After checking your email, copy your password from there and head to the route `api/v1/hosts/reset` with `PATCH` method and fill in your `email(hosts email)`, `password`,`confirm_password` and `old_password` from your email and send.

9. To add an accommodation head to the route `api/v1/accommodations/hosts` with `POST` method fill in`accommodation_name`, `description`,`location`,`services`in an array format ex: `[{"service":"Cab"}]` then also fill in`amenities` in an array format too `[{"amenity":"Swimming Pool"}]` finally do not forget to add `images` because an accommodation without pictures is simply irrelevant to our clients that's why I ensured that Host must add more than one picture so go ahead and select more than one picture in that same `images` field then Send request.

10. In order to view all accommodations head to the route `api/v1/accommodations`, `GET` method and pick up your id from there.

11. After creating accommodation, head to the route `api/v1/accommodations/rooms` and fill in the
`accommodation_id`,`name`,`room_type`,`description`,`cost`,`status` and `images` here also you have to upload more than one image so select more than one in the same input field.

12. You will realise that after creating your room if you try to view this specific accommodation  head to `api/v1/accommodations/:<accoommodation_id>` `GET` method you will realise that the available spaces have increased.

13. To view all rooms within an accommodation head to `api/v1/accommodations/:<accoommodation_id>/rooms` `GET` method

14. To view a specific room within an accommodation head to `api/v1/accommodations/:<accoommodation_id>/rooms/:<roomid>` `GET` method

15. finally to fetch all accommodations within a location head to `/api/v1/accommodations/locations/:<locationid>`, `GET` method
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168050026](https://www.pivotaltracker.com/story/show/168050026)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
SUPER ADMIN ADD HOST
Screen Shot 2019-09-30 at 15 15 11
HOST RESET HIS PASSWORD
Screen Shot 2019-09-30 at 15 15 23
HOST ADD ACCOMMODATION
Screen Shot 2019-09-30 at 15 16 33
HOST ADD ROOM TO HIS ACCOMMODATION
Screen Shot 2019-09-30 at 15 16 46

#### Questions:
N/A

### CODE REVIEW

**Review by amilykassim — APPROVED** [review]
LGTM!

**Review by gik-hub — APPROVED** [review]
Oh, this is great  @Jordybastien 

Remove only the console in the Host.spec and come commented code in the mail.helper

**Comment by Jordybastien** [comment]
@TgeeT  Thank you for your review, Resolved

**Review by Paulvitalis200 — CHANGES_REQUESTED** [review]
When you add an `accommodation`,` a room`, or the `host`, the status code should be `201` because you have created a resource.

**Review by Paulvitalis200 — APPROVED** [review]

**Pull request merged**
