### PR TITLE
#168049985 Setup Sequelize

### PR DESCRIPTION
**Pull request by mucyomiller**
#### What does this PR do?
Setup Sequelize
#### Description of Task to be completed?
  - add sequelize configurations
  - add dummy model & it's migration file
  - add configuration instructions in README
 -  add feedback from TTL
#### How should this be manually tested?
1) clone repository
```shell
$ git clone https://github.com/andela/technites-bn-backend
```
2) checkout into this branch 
```shell
$ git checkout ch-setup-sequelize-168049985
``` 
3) create database locally eg:
```shell
$ createdb barebootnomad_db
``` 
4) remember to set DB configs respectively in .env file as described in .env.example .  

5) run migration :
```shell
$ npm run migrate
```
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168049985](https://www.pivotaltracker.com/story/show/168049985)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by Jordybastien — APPROVED** [review]
LGTM

**Review by gik-hub — APPROVED** [review]
Great work.

**Review by didasmbalanya — APPROVED** [review]

**Review by amilykassim — APPROVED** [review]
LGTM

**Review by Paulvitalis200 — APPROVED** [review]
Good work Fred.

**Pull request merged**
