### PR TITLE
#168238483 Add a pull request template

### PR DESCRIPTION
**Pull request by gik-hub**
#### What does this PR do?
This PR adds a pull request template
#### Description of Task to be completed?
Add a pull request remplate in a .github folder
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168238483](https://www.pivotaltracker.com/story/show/168238483)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by Jordybastien — APPROVED** [review]
LGTM

**Comment by gik-hub** [comment]
I did a force push since there were some changes which had not been autosaved. Will be keen not to repeat the same next time

**Review by didasmbalanya — APPROVED** [review]

**Review by mucyomiller — APPROVED** [review]
Looks good to me 👍

**Review by amilykassim — APPROVED** [review]
Great!

**Review by Paulvitalis200 — COMMENTED** [review]
Awesome work @TgeeT. However, capitalize the first letter of the PR title before I can approve and merge it.

**Review by Paulvitalis200 — COMMENTED** [review]
Also, amend your commit to be something like `setup-pr` and not `PR`

**Review by Paulvitalis200 — APPROVED** [review]
Good work implementing the feedback.

**Pull request merged**
