### PR TITLE
#168050007 Users should be able to make multi city request

### PR DESCRIPTION
**Pull request by amilykassim**
#### What does this PR do?
- Allow users to make a multi-city request
#### Description of Task to be completed?
- Implement making a multi-city request with all the appropriate validations
#### How should this be manually tested?
1. Start by cloning repository
`git clone https://github.com/andela/technites-bn-backend.git`

2. Then checkout to this branch
`git checkout ft-request-multi-city-168050007`

3. Run `npm run migrate`

4. Run `npm run seed` this will add two locations with id `1` and `2` that you will need in testing the feature.

5. Start server  `npm run  dev`

6. Create a request at this endpoint `api/v1/requests/`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168050007](https://www.pivotaltracker.com/story/show/168050007)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
*Create multi city request*
Screen Shot 2019-09-25 at 15 08 29

#### Questions:
N/A

### CODE REVIEW

**Review by Jordybastien — COMMENTED** [review]
The feature is well implemented, however just remove the `[Start #168050007]` in the beginning of the PR description and `npm run install` as we do not have such script, also make the validations on destinations more robust
Keep up the good work

**Review by gik-hub — CHANGES_REQUESTED** [review]
Great work @amilykassim , I like the validations you have put in place. However, thre are two slight changes I would like you to factor in:
1. Currently one can have a departure date in the past which is not practical. Get a function to compare the departure date against the current time to ensure there is sanity in our database
cheat sheet => future dates are always greater than past dates
2. Once a request is created, a duplicate request can be added multiple times which is not required. You can check this against the reason and the departure date so that if they are identical, then the request already exists and should not be added in the database.

**Review by Jordybastien — APPROVED** [review]

**Comment by amilykassim** [comment]
Ok let me work on that!

**Review by gik-hub — APPROVED** [review]
Awesome Bro, your feature is now rocking :boom:

**Review by Paulvitalis200 — APPROVED** [review]

**Pull request merged**
