### PR TITLE
#168049986 Configuring ESLint

### PR DESCRIPTION
**Pull request by Jordybastien**
#### What does this PR do?
This PR contains ESLint Configuration
#### Description of Task to be completed?
Setup ESLint
#### How should this be manually tested?
After installing all required package open any script
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[168049986](https://www.pivotaltracker.com/story/show/168049986)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by mucyomiller — APPROVED** [review]
Looks good 👍

**Review by didasmbalanya — APPROVED** [review]

**Review by gik-hub — APPROVED** [review]
Okay,..

**Review by amilykassim — APPROVED** [review]

**Review by Paulvitalis200 — COMMENTED** [review]
Hey @Jordybastien good work on this. Please amend your commit naming to follow the Andela best practices handbook. The scope section should be something like `setup-eslint` and not `ch`.

**Review by Paulvitalis200 — COMMENTED** [review]
Amend your commit to remove the part `finishes #168049986` from the title of the commit.

**Comment by Jordybastien** [comment]
> Hey @Jordybastien good work on this. Please amend your commit naming to follow the Andela best practices handbook. The scope section should be something like `setup-eslint` and not `ch`.

Feedback implemented @Paulstar200 , thank you

**Comment by Jordybastien** [comment]
> Amend your commit to remove the part `finishes #168049986` from the title of the commit.

Feedback implemented @Paulstar200 , thank you

**Review by Paulvitalis200 — APPROVED** [review]
Good work implementing the feedback.

**Pull request merged**
