### PR TITLE
#168050008  Notifications for new travel request

### PR DESCRIPTION
**Pull request by amilykassim**
#### What does this PR do?
This feature allows a user to receive in-app notifications and email notifications
#### Description of Task to be completed?

- Create a request
- Receive or block in-app notifications
- Receive or block email notifications

#### How should this be manually tested?
1. Start by cloning repository
`git clone https://github.com/andela/technites-bn-backend.git`

2. Then checkout to this branch
`git checkout ft-notification-new-travel-request-168050008`

3. Run `npm i`

4. a) Run `npm run migrate:refresh`
    b) Run `npm run seed`

5. Start server  `npm run  dev`

7. Now create an account on this endpoint using POST : `/api/v1/auth/register/`

8. Now login on this endpoint using POST : `/api/v1/auth/login/`

9. Create a request on this endpoint using POST : `/api/v1/requests/`

10. Open the browser's tab on port 3000

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#168050008](https://www.pivotaltracker.com/story/show/168050008)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
*In-app notification*
Screen Shot 2019-10-02 at 13 13 49

*Creating request and receiving in-app notification and email notification*
Screen Shot 2019-10-02 at 13 12 45

#### Questions:
N/A

### CODE REVIEW

**Comment by Jordybastien** [comment]
PR description not complete @amilykassim

**Review by Jordybastien — COMMENTED** [review]
LGTM, however if you could see how to change the BASE URL for production environment that would be cool

**Comment by amilykassim** [comment]
> LGTM, however if you could see how to change the BASE URL for production environment that would be cool

> Yeah that will be effective but unfortunately you can handle that while using React because the plain javascrlpt doesn't have that option as NODE has it.

**Review by mucyomiller — APPROVED** [review]
LGTM

**Review by Jordybastien — APPROVED** [review]

**Comment by amilykassim** [comment]
> PR description not complete @amilykassim

Thanks a lot, @Jordybastien for taking time to review the PR and raising the issue, if you don't mind, could you let me know what is missing in the PR description so that I can actually add it.

**Pull request closed without merging**
