### PR TITLE
#169033038 User should be able to get all notifications

### PR DESCRIPTION
**Pull request by amilykassim**
#### What does this PR do?

- Get all notifications of a user

#### Description of Task to be completed?

- Get all notifications of a user
- Get all unread notifications of a user
- Get all read notifications of a user

#### How should this be manually tested?
1. Start by cloning repository
`git clone https://github.com/andela/technites-bn-backend.git`

2. Then checkout to this branch
`git checkout ft-get-all-notifications-169033038`

3. a) Run `npm run migrate:refresh`
    b) Run `npm run seed`

4. Start server  `npm run  dev`

5. Now get all the notifications on this endpoint using GET : `/api/v1/users/notifications`

6. Now get all UNREAD notifications on this endpoint using GET : `/api/v1/users/notifications?seen=false`

7. Now get all READ notifications on this endpoint using GET : `/api/v1/users/notifications?seen=true`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169033038](https://www.pivotaltracker.com/story/show/169033038)
#### What are the relevant Github Issues?
N/A
#### Screenshots (if appropriate)
*ALL NOTIFICATIONS*
Screen Shot 2019-10-10 at 16 56 52

*ALL READ NOTIFICATIONS*
Screen Shot 2019-10-10 at 16 56 07

*ALL UNREAD NOTIFICATIONS*
Screen Shot 2019-10-10 at 16 56 34

#### Questions:
N/A

### CODE REVIEW

**Review by gik-hub — APPROVED** [review]
Hey great work.
But I realized you have not included a request_id field in your notifications table which we had agreed to add. Please add it

**Review by gik-hub — CHANGES_REQUESTED** [review]
Please add the request_id in the notifications table.

Additionally, I have made the implementation a bit scalable by separating the notification logic  and client, you can sync with me on the same

**Review by mucyomiller — COMMENTED** [review]
Try to increase your test coverage also

Great, The issue was fixed. feel free to review it again.

**Comment by amilykassim** [comment]
> Hey great work.
> But I realized you have not included a request_id field in your notifications table which we had agreed to add. Please add it

I resolved it. review again

**Review by didasmbalanya — APPROVED** [review]

**Comment by amilykassim** [comment]
> Please add the request_id in the notifications table.
> 
> Additionally, I have made the implementation a bit scalable by separating the notification logic and client, you can sync with me on the same

Thanks for that, and I've worked on it, so it is fixed now.

**Review by gik-hub — APPROVED** [review]
LGTM Now

**Review by Paulvitalis200 — APPROVED** [review]

**Pull request merged**
